spring:
  http:
    multipart:
      max-request-size: 100Mb
      max-file-size: 20Mb
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost/procheck?useSSL=false&characterEncoding=utf8
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
