spring:
  http:
    servlet:
      max-request-size: 100Mb
      max-file-size: 20Mb
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/procheck?useSSL=false&characterEncoding=utf8
    username: root
    password: yq199410
    backupPath: D:/workstation/procheck/sql/

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
site:
  uploadPath: D:/workstation/procheck/ueditor/
  uploadName: /upload/
  imagePath: D:/workstation/procheck/images/
  imageName: /images/

